#!/bin/bash
set -e

echo $USER

# Cloudron defaults & Env Mappings
export ALLOW_REGISTRATION="false"
export DOMAIN=${CLOUDRON_WEBADMIN_ORIGIN#https://my.}
export DOMAIN_APP=${CLOUDRON_APP_DOMAIN}
export AUTHENTICATION="ldap"
export LDAP_BASE=${CLOUDRON_LDAP_USERS_BASE_DN}
export LDAP_SERVER=${CLOUDRON_LDAP_SERVER}:${CLOUDRON_LDAP_PORT}
export LDAP_ROOTDN=${CLOUDRON_LDAP_BIND_DN}
export LDAP_PASSWORD=${CLOUDRON_LDAP_BIND_PASSWORD}
export LDAP_FILTER='(&(objectclass=user)(|(username=$user)(mail=$user)))'
export LDAP_ADMIN_FILTER="(&(objectclass=user)(memberof=cn=employees,ou=groups,dc=cloudron))" # TODO: How to find admins in LDAP?
export TURN_SERVER=${CLOUDRON_TURN_SERVER}
export TURN_SECRET=${CLOUDRON_TURN_SECRET}

export LOG_LEVEL="info"

export DOMAIN_HTTP_UPLOAD=${DOMAIN_HTTP_UPLOAD:-"upload.$DOMAIN"}
export DOMAIN_MUC=${DOMAIN_MUC:-"conference.$DOMAIN"}
export DOMAIN_PROXY=${DOMAIN_PROXY:-"proxy.$DOMAIN"}
export DOMAIN_PUBSUB=${DOMAIN_PUBSUB:-"pubsub.$DOMAIN"}
export DB_DRIVER=${DB_DRIVER:-"SQLite3"}
export DB_DATABASE=${DB_DATABASE:-"prosody.sqlite"}
export E2E_POLICY_CHAT=${E2E_POLICY_CHAT:-"optional"}
export E2E_POLICY_MUC=${E2E_POLICY_MUC:-"optional"}
export E2E_POLICY_WHITELIST=${E2E_POLICY_WHITELIST:-""}
export LOG_LEVEL=${LOG_LEVEL:-"info"}
export C2S_REQUIRE_ENCRYPTION=${C2S_REQUIRE_ENCRYPTION:-true}
export S2S_REQUIRE_ENCRYPTION=${S2S_REQUIRE_ENCRYPTION:-true}
export S2S_SECURE_AUTH=${S2S_SECURE_AUTH:-true}
export SERVER_CONTACT_INFO_ABUSE=${SERVER_CONTACT_INFO_ABUSE:-"xmpp:abuse@$DOMAIN"}
export SERVER_CONTACT_INFO_ADMIN=${SERVER_CONTACT_INFO_ADMIN:-"xmpp:admin@$DOMAIN"}
export SERVER_CONTACT_INFO_FEEDBACK=${SERVER_CONTACT_INFO_FEEDBACK:-"xmpp:feedback@$DOMAIN"}
export SERVER_CONTACT_INFO_SALES=${SERVER_CONTACT_INFO_SALES:-"xmpp:sales@$DOMAIN"}
export SERVER_CONTACT_INFO_SECURITY=${SERVER_CONTACT_INFO_SECURITY:-"xmpp:security@$DOMAIN"}
export SERVER_CONTACT_INFO_SUPPORT=${SERVER_CONTACT_INFO_SUPPORT:-"xmpp:support@$DOMAIN"}
export PROSODY_ADMINS=${PROSODY_ADMINS:-""}